// Generated by Wrangler on Tue Aug 13 2024 15:30:20 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-export interface CloudflareBindings`

export interface CloudflareBindings {
	API_HOST: "example.com";
	SECRET_KEY: string;
	API_TOKEN: string;
	R2_BUCKET: R2Bucket;
	D1_DB: D1Database;
}
