// Generated by Wrangler on Tue Aug 13 2024 01:03:18 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-export interface CloudflareBindings`

export interface CloudflareBindings {
	API_HOST: "example.com";
	SECRET_KEY: string;
	API_TOKEN: string;
	D1_DB: D1Database;
}
